import { ImageSourcePropType } from 'react-native';

// PT2 — the photographic practice-tile set (generated by Cat from
// Rally21-Practice-Imagery-Prompts.md's locked style block), one square
// image per practice type, keyed EXACTLY by type key. Single require()
// point per the asset-family convention; static requires only, so web
// and native both bundle them (no network fetch at render time).
//
// Downscaled to 512×512 JPEG at bundle time (the originals are 1254px
// PNGs, ~2 MB each — the masters live outside the repo in the project's
// design folder). A type with no entry here renders the emoji-on-mint
// treatment instead — never a broken image (see the browse grid's
// fallback in create-circle.tsx).
//
// PT3 (17 July): the map now covers the full 18-key table — every type
// has its tile (eat's master landed; unplug retired with its file, so
// the browse never shows it again). Kept as a plain string map so a
// bundle running ahead of (or behind) a schema change degrades to the
// emoji fallback instead of a type error.
//
// PB1 (21 July): 'selfcare' reinstated (19th key) with NO entry here on
// purpose — it renders the emoji fallback until Cat generates
// selfcare.jpg (Rally21-Practice-Imagery-Prompts.md carries the subject
// line); add the require() below when the file lands.
export const PRACTICE_TILES: Record<string, ImageSourcePropType> = {
  walk: require('./walk.jpg'),
  run: require('./run.jpg'),
  stretch: require('./stretch.jpg'),
  strength: require('./strength.jpg'),
  sport: require('./sport.jpg'),
  dance: require('./dance.jpg'),
  meditate: require('./meditate.jpg'),
  breathe: require('./breathe.jpg'),
  journal: require('./journal.jpg'),
  gratitude: require('./gratitude.jpg'),
  affirm: require('./affirm.jpg'),
  read: require('./read.jpg'),
  language: require('./language.jpg'),
  study: require('./study.jpg'),
  music: require('./music.jpg'),
  write: require('./write.jpg'),
  art: require('./art.jpg'),
  eat: require('./eat.jpg'),
};
