import { ImageSourcePropType } from 'react-native';

// PT2 — the photographic practice-tile set (generated by Cat from
// Rally21-Practice-Imagery-Prompts.md's locked style block), one square
// image per practice type, keyed EXACTLY by type key. Single require()
// point per the asset-family convention; static requires only, so web
// and native both bundle them (no network fetch at render time).
//
// Downscaled to 512×512 JPEG at bundle time (the originals are 1254px
// PNGs, ~2 MB each — the masters live outside the repo in the project's
// design folder). A type with no entry here renders the emoji-on-mint
// treatment instead — never a broken image (see the browse grid's
// fallback in create-circle.tsx).
//
// Deliberately keyed as a plain string map, not Record<PracticeTypeKey,…>:
// the set Cat generated tracks the taxonomy spec's 16 July revision
// (affirm added), which is one step ahead of the shipped 29-key
// taxonomy — affirm.jpg is bundled and ready but unreachable until a
// migration adds the 'affirm' key. eat.png was not in the drop; care/eat
// falls back to emoji until it lands.
export const PRACTICE_TILES: Record<string, ImageSourcePropType> = {
  walk: require('./walk.jpg'),
  run: require('./run.jpg'),
  stretch: require('./stretch.jpg'),
  strength: require('./strength.jpg'),
  sport: require('./sport.jpg'),
  dance: require('./dance.jpg'),
  meditate: require('./meditate.jpg'),
  breathe: require('./breathe.jpg'),
  journal: require('./journal.jpg'),
  gratitude: require('./gratitude.jpg'),
  unplug: require('./unplug.jpg'),
  affirm: require('./affirm.jpg'),
  read: require('./read.jpg'),
  language: require('./language.jpg'),
  study: require('./study.jpg'),
  write: require('./write.jpg'),
  art: require('./art.jpg'),
  music: require('./music.jpg'),
};
